Device: cuda:0
this is num of close 1000
this is num of normal 1000
begin!
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/knolling_bot/resnet/data_train.py", line 223, in <module>
    pred_lwcossin = model.forward(img).reshape(BATCH_SIZE, max_item, 7)
  File "/home/ubuntu/Desktop/knolling_bot/network.py", line 106, in forward
    x = self.layer3(x)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/Desktop/knolling_bot/network.py", line 52, in forward
    x = self.conv3(x)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/anaconda3/envs/deeplearning/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 10.73 GiB total capacity; 6.80 GiB already allocated; 74.50 MiB free; 6.83 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF